.github/workflows/dbt_alter_gha_tasks.yml
.github/workflows/dbt_docs_update.yml
.github/workflows/dbt_run_adhoc.yml
.github/workflows/dbt_run_dev_refresh.yml

- Adding standard GHA workflows to the project
- Currently `dev_refresh` has both a CRON and a SF task schedule. The SF schedule will be removed eventually and is not active. I needed something as a placeholder because the seed file cannot be empty when deploying the GHA setup

add workflows

---

macros/dbt/get_merge.sql
macros/dbt/get_tmp_relation_type.sql
models/descriptions/_inserted_timestamp.md
models/descriptions/_invocation_id.md
models/descriptions/block_id.md
models/descriptions/block_timestamp.md
models/descriptions/inserted_timestamp.md
models/descriptions/modified_timestamp.md
models/descriptions/pk.md
models/github_actions/github_actions__current_task_status.yml
models/silver/core/silver__blocks.sql
models/silver/core/silver__blocks.yml
tests/test_silver__blocks_gaps.sql

- Add `silver.blocks` model
- Add schema docs + tests
- Add gaps test (this is expected to fail ATM because we are not backfilled)
- Rename `tests` to `data_tests` to conform w/ `dbt 1.8.x` standards
Incremental on M
```
16:33:16  1 of 1 OK created sql incremental model silver.blocks .......................... [SUCCESS 199999 in 9.23s]
```
Tests
```
16:40:15  Finished running 1 incremental model, 15 data tests, 5 project hooks in 0 hours 0 minutes and 21.54 seconds (21.54s).
16:40:15  
16:40:15  Completed with 1 error and 0 warnings:
16:40:15  
16:40:15  Failure in test test_silver__blocks_gaps (tests/test_silver__blocks_gaps.sql)
16:40:15    Got 1 result, configured to fail if != 0
16:40:15  
16:40:15    compiled code at target/compiled/eclipse_models/tests/test_silver__blocks_gaps.sql …
```

Silver blocks

---

macros/create_udfs.sql
macros/python/udfs.sql
models/descriptions/address_table_lookups.md
models/descriptions/inner_instruction.md
models/descriptions/instruction.md
models/descriptions/log_messages.md
models/descriptions/partition_key.md
models/descriptions/post_balances.md
models/descriptions/post_token_balances.md
models/descriptions/pre_balances.md
models/descriptions/pre_token_balances.md
models/descriptions/recent_block_hash.md
models/descriptions/signers.md
models/descriptions/tx_account_keys.md
models/descriptions/tx_fee.md
models/descriptions/tx_id.md
models/descriptions/tx_index.md
models/descriptions/tx_size.md
models/descriptions/tx_succeeded.md
models/descriptions/tx_unit_limit.md
models/descriptions/tx_units_consumed.md
models/descriptions/tx_version.md
models/silver/core/silver__transactions.sql
models/silver/core/silver__transactions.yml

- Add `silver.transactions`
- Now includes `index` to indicate execution order within a given block
- Currently there is no way to include the block timestamp from the RPC call using explode keys with streamline 2.0, therefore we have to keep the join to blocks + null timestamp self-heal logic
- Add UDFs needed for `silver.transactions`
Incremental and tests on M
```
15:29:29  Finished running 1 incremental model, 16 data tests, 5 project hooks in 0 hours 0 minutes and 31.97 seconds (31.97s).
15:29:29  
15:29:29  Completed successfully
15:29:29  
15:29:29  Done. PASS=17 WARN=0 ERROR=0 SKIP=0 TOTAL=17
```
Data in dev
```
select *
from eclipse_dev.silver.transactions
```

Silver transactions

---

models/descriptions/account_index.md
models/descriptions/decimal.md
models/descriptions/mint.md
models/descriptions/token_balances_index.md
models/descriptions/token_owner.md
models/descriptions/ui_amount.md
models/silver/core/silver___post_token_balances.sql
models/silver/core/silver___post_token_balances.yml
models/silver/core/silver___pre_token_balances.sql
models/silver/core/silver___pre_token_balances.yml

- Add `silver._pre_token_balances` and `silver._post_token_balances`
- Omitting `_instructions` and `_inner_instructions`
- `_instructions` only used in `silver.events`, will just include it as a CTE in the model logic
- `_inner_instructions` will be refactored and surfaced as a regular model `silver.inner_instructions`
Incremental and tests on M
```
15:49:36  Finished running 2 incremental models, 36 data tests, 5 project hooks in 0 hours 0 minutes and 25.43 seconds (25.43s).
15:49:36  
15:49:36  Completed successfully
15:49:36  
15:49:36  Done. PASS=38 WARN=0 ERROR=0 SKIP=0 TOTAL=38
```
Can view on DEV
```
select *
from eclipse_dev.silver._pre_token_balances;
select *
from eclipse_dev.silver._post_token_balances;
```

Silver internal

---

models/descriptions/vote_account.md
models/descriptions/vote_authority.md
models/descriptions/vote_index.md
models/descriptions/vote_state_update.md
models/silver/core/silver__votes.sql
models/silver/core/silver__votes.yml

- Add `silver.votes`
- Include `vote_state_update` as a json column
- Now includes `index` to indicate execution order within a given block
- Now includes `vote_index` to indicate execution order within a given transaction
Incremental and tests on M
```
dbt build -s models/silver/core/silver__votes.sql -t dev
16:27:24  Finished running 1 incremental model, 18 data tests, 5 project hooks in 0 hours 1 minutes and 41.46 seconds (101.46s).
16:27:24  
16:27:24  Completed successfully
16:27:24  
16:27:24  Done. PASS=19 WARN=0 ERROR=0 SKIP=0 TOTAL=19
```

Silver votes

---

macros/create_udfs.sql
macros/python/udfs.sql
models/descriptions/event_index.md
models/descriptions/event_type.md
models/descriptions/inner_instruction_index.md
models/descriptions/inner_instruction_program_ids.md
models/descriptions/program_id.md
models/silver/core/silver__events.sql
models/silver/core/silver__events.yml
models/silver/core/silver__inner_instructions.sql
models/silver/core/silver__inner_instructions.yml

- Add `silver.events`
- Add `silver.inner_instructions`
Incremental and tests on M
`dbt build -s silver__events silver__inner_instructions -t dev`
```
15:06:16  Finished running 2 incremental models, 26 data tests, 5 project hooks in 0 hours 0 minutes and 29.32 seconds (29.32s).
15:06:17  
15:06:17  Completed successfully
15:06:17  
15:06:17  Done. PASS=28 WARN=0 ERROR=0 SKIP=0 TOTAL=28
```
Data in DEV
```
select *
from eclipse_dev.silver.events;
select *
from eclipse_dev.silver.inner_instructions;
```

Silver events

---

models/silver/core/silver__blocks.sql
models/silver/core/silver__transactions.sql

- Add usage of `bronze__FR_*` views when doing full refreshes on `bronze_blocks` and `bronze_transactions`
FRs and Incrementals
```
-- blocks
16:57:16  Finished running 1 incremental model, 5 project hooks in 0 hours 0 minutes and 12.96 seconds (12.96s).
16:57:16  
16:57:16  Completed successfully
16:57:16  
16:57:16  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
16:57:53  Finished running 1 incremental model, 5 project hooks in 0 hours 0 minutes and 12.27 seconds (12.27s).
16:57:53  
16:57:53  Completed successfully
16:57:53  
16:57:53  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
-- transactions
16:58:36  Finished running 1 incremental model, 5 project hooks in 0 hours 0 minutes and 26.91 seconds (26.91s).
16:58:36  
16:58:36  Completed successfully
16:58:36  
16:58:36  Done. PASS=1 WARN=0 …
```

add FR views

---

.github/workflows/dbt_run_incremental_core.yml
.github/workflows/dbt_run_incremental_non_core.yml
data/github_actions__workflows.csv
models/bronze/prices/bronze__complete_native_prices.sql
models/descriptions/gold/stats/ez_core_metrics.md
models/gold/stats/stats__ez_core_metrics_hourly.sql
models/gold/stats/stats__ez_core_metrics_hourly.yml
models/silver/prices/silver__complete_native_prices.sql
models/silver/prices/silver__complete_native_prices.yml
models/silver/stats/silver__core_metrics_hourly.sql
models/silver/stats/silver__core_metrics_hourly.yml
models/sources.yml

- Add `stats` models
- Add native prices using `ethereum` since it is a dependency for `stats__ez_core_metrics_hourly`
- Includes both vote and non-vote txs in the transction count
Run native prices and tests on M
`dbt build -s models/bronze/prices/bronze__complete_native_prices.sql models/silver/prices/silver__complete_native_prices.sql -t dev`
```
15:15:41  Finished running 1 view model, 1 incremental model, 10 data tests, 5 project hooks in 0 hours 0 minutes and 20.31 seconds (20.31s).
15:15:42  
15:15:42  Completed successfully
15:15:42  
15:15:42  Done. PASS=12 WARN=0 ERROR=0 SKIP=0 TOTAL=12
```
Run silver and gold metrics on M
`dbt run -s models/silver/stats/silver__core_metrics_hourly.sql models/gold/stats/stats__ez_core_metrics_hourly.sql -t dev `
```
15:22:55  Finished running 2 …
```

Stats models

---

models/silver/core/silver___post_token_balances.sql
models/silver/core/silver___pre_token_balances.sql
models/silver/core/silver__events.sql
models/silver/stats/silver__core_metrics_hourly.sql

- Add `block_timestamp IS NOT NULL` predicate to models that are direct downstreams of `silver.votes` and `silver.transactions`
DEV events no longer has bad records
```
select tx_id, index
from eclipse_dev.silver.events
group by 1,2
having count(*) > 1;
select min(inserted_timestamp)
from eclipse_dev.silver.events
where block_timestamp is null;
```

don't include txs that come in ahead of blocks

---

.github/workflows/dbt_run_observability.yml
.github/workflows/dbt_run_observability_full.yml
models/silver/_observability/silver_observability__blocks_completeness.sql
models/silver/_observability/silver_observability__blocks_completeness.yml
models/silver/_observability/silver_observability__blocks_tx_count.sql
models/silver/_observability/silver_observability__blocks_tx_count.yml

- Add `observability` models
- transaction completeness is omitted at this time because there is no 3rd party source to compare
full observe
`dbt run --vars '{"OBSERV_FULL_TEST":True}' -s "eclipse_models,tag:observability`
```
15:51:46  Finished running 2 incremental models, 5 project hooks in 0 hours 0 minutes and 15.46 seconds (15.46s).
15:51:47  
15:51:47  Completed successfully
15:51:47  
15:51:47  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```
incremental observe
`dbt build -s "eclipse_models,tag:observability"`
```
15:55:52  Finished running 2 incremental models, 27 data tests, 5 project hooks in 0 hours 0 minutes and 21.31 seconds (21.31s).
15:55:53  
15:55:53  Completed successfully
15:55:53  
15:55:53  Done. PASS=29 WARN=0 ERROR=0 SKIP=0 TOTAL=29
```

Silver observability

---

.github/workflows/dbt_test_daily.yml
tests/test_silver__blocks_gaps.sql

- Add daily test workflow
- Modify block gaps tests to ignore blocks that we have not backfilled yet
ran test command against existing prod locally
```
15:43:55  Finished running 333 data tests, 5 project hooks in 0 hours 1 minutes and 59.71 seconds (119.71s).
15:43:55  
15:43:55  Completed successfully
15:43:55  
15:43:55  Done. PASS=333 WARN=0 ERROR=0 SKIP=0 TOTAL=333
```

Add test workflow

---

models/silver/core/silver__transactions.sql
models/silver/core/silver__votes.sql

- Fix issue with sparse data causing dupes when only 1 record in incremental and we have not yet received the block record causing the `min(block_timestamp)` predicate to return `NULL`

sparse data causing dupes when only 1 record and null tiemstamp

---

models/streamline/core/realtime/streamline__block_txs_realtime.sql
models/streamline/core/streamline__node_min_block_available.sql

- Change service node in min block available view so we can start backfilling data from before block `6572203`
- Start with blocks backfill, keep transactions at block `>= 6572203`

Enable block backfill

---

models/gold/defi/defi__fact_solar_dex_tvl.sql
models/gold/defi/defi__fact_solar_dex_tvl.yml

- exclude NULL responses from LQ call
- lower recency test to sooner catch issues with the call failing
Results from run in dev:

filter out null response in solar_dex LQ

---

models/silver/core/silver__blocks.sql
models/streamline/core/complete/streamline__blocks_complete.sql
models/streamline/core/streamline__chainhead.sql

- exclude block responses with `NULL` data from landing in `complete` and `silver` models
- add 50 blocks buffer to `chainhead` call for situations where the most current block doesn't return data
Test succeeded on `silver.blocks` and `core.fact_blocks` after rerunning with new logic:
```
19:29:58  Finished running 39 data tests, 5 project hooks in 0 hours 0 minutes and 47.17 seconds (47.17s).
19:29:58  
19:29:58  Completed successfully
19:29:58  
19:29:58  Done. PASS=39 WARN=0 ERROR=0 SKIP=0 TOTAL=39
```

filter out null responses; add buffer to realtime

---

models/streamline/core/complete/streamline__block_txs_complete.sql

Model runs 4x faster with partition_key filter
```
17:29:00  Finished running 1 incremental model, 5 project hooks in 0 hours 3 minutes and 38.25 seconds (218.25s).
17:29:00  
17:29:00  Completed successfully
17:29:00  
17:29:00  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

add partition_key filter

---

models/silver/stats/silver__core_metrics_hourly.sql

Add 1 hour buffer to blocks/tx/votes selected
- The most recent hour record consistently returns `null` col values for the tx/vote metrics. This is because txs/votes land in our tables up to an hour later then blocks, so no tx/vote specific data exists and results in `null` values

add 1 hour buffer

---

models/silver/program_logs/silver__transaction_logs_program_data.sql

Exclude transactions with NULL `block_timestamps`
- These are eventually handled in `silver.transactions`, so exclude the initial ones. Same logic exists in other models downstream from transactions

exclude null block timestamp txs

---

models/streamline/core/complete/streamline__block_txs_complete.sql
models/streamline/core/realtime/streamline__block_txs_realtime.sql

Make partition key smaller so that we scan less files in silver ingestion

make partitions smaller for streamline block txs requests

---

models/streamline/core/realtime/streamline__block_txs_realtime.sql

Make each worker use `async_concurrent_requests` for getting block transactions to reduce worker run times which will allow us to process more blocks per worker
Process 500 blocks in ~200s vs. 500 blocks in ~500s in production

Have each block txs worker make parallel requests

---

models/gold/core/core__fact_events.sql
models/gold/core/core__fact_events_inner.sql
models/gold/core/core__fact_transactions.sql
models/gold/core/core__fact_transfers.sql

Add SO on commonly used columns, as well as columns in long-running queries used in the State of Eclipse dashboard.
- For fact_transactions, I tried out both `EQUALITY(log_messages)` (for exact searches, like ARRAY_CONTAINS)  and `SUBSTRING(log_messages)` (for text searches using LIKE '%some_text%'). They have different use cases but the speed increase seemed to be the same, so I decided to only add Equality for now.
example queries used for `log_messages` testing:
`alter table eclipse_dev.core.fact_transactions add SEARCH OPTIMIZATION ON EQUALITY(log_messages);`
`alter table eclipse_dev.core.fact_transactions add SEARCH OPTIMIZATION ON SUBSTRING(log_messages);`
```
with a as (select tx_id as logs_tx_id, replace(logs.value, 'Program log: Instruction: ', '') as instructions
from …
```

add additional cols for SO

---

models/silver/core/silver__transactions.sql
models/silver/core/silver__transactions.yml

Update incremental predicate to update tx's with null block_timestamps as existing logic would never update them. This results in duplicate tx_ids with and without a block_timestamp
- add test for unique tx_id that is based on _inserted_timestamp
incremental run:
`1 of 1 OK created sql incremental model silver.transactions .................... [SUCCESS 176849242 in 592.06s]`
test now correctly catches duplicate ids
```
22:44:16  Completed with 1 error and 0 warnings:
22:44:16  Failure in test unique_silver__transactions_TX_ID (models/silver/core/silver__transactions.yml)
22:44:16    Got 8003775 results, configured to fail if != 0
```
All tx_ids with null block_timestamps have a duplicate with correct block_timestamp, so I will manually delete the former ones. query that confirms:
```
WITH …
```

update incremental due to null timestamps

---

.github/workflows/dbt_run_streamline_block_txs_realtime_2.yml
data/github_actions__workflows.csv
macros/streamline/models.sql
models/bronze/streamline/core/bronze__FR_transactions_2.sql
models/bronze/streamline/core/bronze__transactions_2.sql
models/sources.yml
models/streamline/core/complete/streamline__block_txs_complete_2.sql
models/streamline/core/realtime/streamline__block_txs_realtime_2.sql

New block_txs pipeline to make use of `include_top_level_json` parameter
- Run in parallel with legacy pipeline
`dbt run -s streamline__block_txs_complete_2 streamline__block_txs_realtime_2 --vars '{STREAMLINE_INVOKE_STREAMS: True}' -t dev`
```
21:34:38  1 of 2 OK created sql incremental model streamline.block_txs_complete_2 ........ [SUCCESS 20 in 7.94s]
21:34:38  2 of 2 START sql view model streamline.block_txs_realtime_2 .................... [RUN]
21:34:38  Running macro `if_data_call_function`: Calling udf streamline.udf_bulk_rest_api_v2 with params: 
{
"async_concurrent_requests": "10",
"exploded_key": "[\"result.transactions\"]",
"external_table": "block_txs_2",
"include_top_level_json": "[\"result.blockTime\"]",
"order_by_column": "block_id",
"producer_batch_size": "20000", …
```

An 5793/block txs timestamp

---

models/streamline/core/complete/streamline__block_txs_complete.sql

Fix issue when there are gaps before the current `max()` in the completed table which then causes the window of requests to become static and request the same blocks over and over
`dbt run -s streamline__block_txs_complete -t prod`
```
16:26:00  1 of 1 OK created sql incremental model streamline.block_txs_complete .......... [SUCCESS 20500 in 104.69s]
```

get min partition same as what the request view would do

---

models/silver/core/silver__transactions.sql
models/silver/core/silver__votes.sql

- Update silver.transactions to use v2 block txs data after cutoffs
- Update silver.votes to use v2 block txs data after cutoffs
inc runs:
```
20:29:47  1 of 1 OK created sql incremental model silver.transactions .................... [SUCCESS 5543033 in 174.67s]
20:32:46  1 of 1 OK created sql incremental model silver.votes ........................... [SUCCESS 618288 in 103.02s]
```
test run:
```
23:03:00  Finished running 33 data tests, 5 project hooks in 0 hours 5 minutes and 22.25 seconds (322.25s).
23:03:01  Completed successfully
23:03:01  Done. PASS=33 WARN=0 ERROR=0 SKIP=0 TOTAL=33
```
Counts match up with prod:

update txs/votes to use new block txs pipeline

---

models/gold/core/core__fact_blocks.yml
models/gold/core/core__fact_events.yml
models/gold/core/core__fact_events_inner.sql
models/gold/core/core__fact_events_inner.yml
models/gold/core/core__fact_transactions.yml
models/gold/core/core__fact_transfers.yml
models/gold/defi/defi__fact_token_burn_actions.yml
models/gold/defi/defi__fact_token_mint_actions.sql.yml

- remove `unique` column test as the `unique_combination_of_columns` test performs similarly. Update to test last 7 days which we are following in Solana
- keep `unique` test for `blocks` + `transactions` since the pk is made up of those single columns, and update to test for recent values
- remove `_inserted_timestamp` from `events_inner`. Drop it after merge via `ALTER TABLE eclipse.core.fact_events_inner DROP COLUMN _inserted_timestamp;`

update unique test, removed col from events_inner

---

dbt_project.yml

Add change_tracking
- Only stats__ez_core_metrics_hourly.sql needs the `exclude_change_tracking` tag (and it already has it), since it contains logic incompatible with change tracking (ie `GROUP BY`, `UNION`, `QUALIFY`, `LEFT JOIN` logic)

add change tracking
